# Generated by Django 6.0.3 on 2026-03-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bpm', models.FloatField()),
                ('bpm_avg', models.FloatField()),
                ('ir', models.IntegerField()),
                ('ds18b20_temp', models.FloatField()),
                ('dht11_temp', models.FloatField()),
                ('humidity', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
